### ISSUE TITLE
Linux desktop icon

### ISSUE THREAD

**Issue by c0b41** [voltraco/beta#1]
Linux desktop icon broken

**Comment by aprile** [comment]
@c0b41 Right now we're only testing on the latest Ubuntu, what version are you on so we can spin up a vm and test? Thanks!

**Comment by c0b41** [comment]
Ubuntu 14.04
Elementary os Freya

![ekran goruntusu - 2016-09-13 13 18 36](https://cloud.githubusercontent.com/assets/2834954/18470341/c6f4943a-79b4-11e6-96ca-a0b80c4a6c8e.png)

**Comment by heapwolf** [comment]
Does the ubuntu version show the icon? (i was showing up properly for me in previous builds). I was aware that other flavors of linux were missing the icon (not sure why though).

**Comment by c0b41** [comment]
@0x00A I do not know but, not showing any version me. Probably broken electron build.

[electron-builder](https://www.npmjs.com/package/electron-builder) cool, maybe checkout, also rpm build :)

**Comment by heapwolf** [comment]
@c0b41 can you verify that this is still an issue after you reinstall (via #2)?

**Comment by c0b41** [comment]
@0x00A fixed last update
