### ISSUE TITLE
Voltra comes up between monitors

### ISSUE THREAD

**Issue by jberkus** [voltraco/beta#13]
Fedora 23, Gnome 3

This is a pretty minor issue but: when Voltra comes up, the application centers itself on the user's workspace.  If the user has two displays, this means that it comes up split across them, half on each display.  

This is a pretty minor issue, just filing it in case there's a very easy way to fix it.

**Comment by aprile** [comment]
Thanks, this should be easy to fix for the next release.

**Comment by jberkus** [comment]
Thanks.  Speaking of which, is there any more to updating Voltra than just replacing the binaries?

**Comment by jberkus** [comment]
@aprileelcich This issue does not appear to be resolved in 2.20.  Voltra still comes up between monitors. Let me know if there's any system data I can provide you.

**Comment by jberkus** [comment]
Still an issue in 2.5.12, FYI.
