### ISSUE TITLE
Minor issues with soundwave view

### ISSUE THREAD

**Issue by jberkus** [voltraco/beta#15]
If you hit CTRL-T while playing a track, you get a "soundwave" view of the current music playing.  This is pretty cool/fun.  Some minor nits with it you should look at, though:

1. Discoverability: I found it by accident.  Not sure how other users would figure out to hit CTRL-T.
2. Getting out: if a user accidentally gets into soundwave view, it's not clear how to get out of it.  Consider enabling ESC and double-click to exit.
3. Focus: when I take the focus off the Voltra app, the soundwave freezes.  This means the view is really only fun if I'm fullscreening Voltra and not touching my laptop.  It would be good if it continued.

Platform: Linux/Fedora

**Comment by aprile** [comment]
Ah, this is actually a visualization demo for developers interested in making plugins for Voltra. It's not a full feature, which is why it is only discoverable by shortcut :) We will enable ESC for it though, good idea.

**Comment by jberkus** [comment]
Yeah, I only found it becuase I was trying to open a new tab in Firefox, but the focus was actually on Voltra.

**Comment by heapwolf** [comment]
Removed plugins for now.
