### ISSUE TITLE
does not terminate properly on full screen

### ISSUE THREAD

**Issue by watilde** [voltraco/beta#17]
Hello!

When the app is displayed in a full-screen mode and push a close button in the navigation, app screen is gone, and then it's hard to restore the app again in the full-screen mode. I think that the application is operating correctly in the background when users push the close button, but it's a general behaviour to exit the full-screen mode.

![screen_shot_2017-01-12_at_22_10_38](https://cloud.githubusercontent.com/assets/1716463/21908486/317e5a5c-d914-11e6-9c6d-21a8d3101eb2.jpg)

⬇️ 

![screen shot 2017-01-12 at 22 10 40](https://cloud.githubusercontent.com/assets/1716463/21908499/3e168e56-d914-11e6-8c4b-11ee38a2c326.png)

it could be realted to https://github.com/electron/electron/issues/8338

**Comment by aprile** [comment]
Ahh! Good catch, I misunderstood this issue at first but I was able to reproduce and now I see it's going to a black page... 

@0x00A can you investigate?

**Comment by aprile** [comment]
This has been addressed with the last version, thanks @watilde!

**Comment by watilde** [comment]
Thanks!
