### ISSUE TITLE
Consider "Now Playing" being a separate view mode

### ISSUE THREAD

**Issue by matthewmorek** [voltraco/beta#18]
Do you plan on having a permanent view mode for “Now playing” screen? It is currently only available on demand, but I tend to keep it open all the time, yet I have to close it to minimise/hide the app.

I think it would be a nice addition to the rest of the screens, and would reduce a lot of friction with having to jump in/out to see what's next on the list, or maybe shift things around.

What are your thoughts on this?

**Comment by heapwolf** [comment]
I think this is addressed by #19, which is now in the master branch and will ship soon. Closing for now but @matthewmorek let me know what you think about the solution.
