### ISSUE TITLE
Last update broken

### ISSUE THREAD

**Issue by c0b41** [voltraco/beta#2]
Voltra not opening.. 
![ekran goruntusu - 2016-09-13 13 15 01](https://cloud.githubusercontent.com/assets/2834954/18470220/454e6834-79b4-11e6-96e7-d2a60eed70e9.png)

**Comment by heapwolf** [comment]
Thanks for the heads up @c0b41!! Looks like the error...

```
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.20' not found (required by /usr/share/voltra/resources/app/node_modules/taglib2/build/Release/taglib2.node)
```

...is because the `glibc` version on the target computer isn't new enough (i compiled with `g++-4.9` for the last update). I should go back to `g++-4.7` to stay compatible!! We will do a build tonight for linux :)

**Comment by c0b41** [comment]
@0x00A thanks paolo, also why not error log does not seem cli.
this might be helpful 
![ekran goruntusu - 2016-09-13 13 41 51](https://cloud.githubusercontent.com/assets/2834954/18471011/2c46785a-79b8-11e6-82a3-ad7a26a12b87.png)

**Comment by c0b41** [comment]
The problem continues, stuck loading screen ![ekran goruntusu - 2016-10-21 22 06 11](https://cloud.githubusercontent.com/assets/2834954/19608532/ae242f30-97da-11e6-97eb-1e182669af83.png)

**Comment by heapwolf** [comment]
looks like a different issue this time -- did you install it with something like `sudo gdebi ./installers/voltra_1.11.0_amd64.deb`?

**Comment by c0b41** [comment]
@0x00A `sudo dpkg -i voltra.deb`

**Comment by heapwolf** [comment]
looks like putting it into `/user/share/voltra` worked for arch linux. do you know where the executable got placed?

**Comment by heapwolf** [comment]
I just realized i gave that tester a `.tar.gz`, maybe it would be easier to distribute a tarball than an installer given that there is so much variance between linux flavors.

**Comment by c0b41** [comment]
@0x00A how to fresh install voltra? seem  like a conflict before config ..

**Comment by heapwolf** [comment]
@c0b41 you should now be able to download a `tar.gz` from the original download page. If you extract all the files from the tarball into `/user/share/voltra` it should work fine.

**Comment by c0b41** [comment]
@0x00A thanks, fixed last update my fault 👍

**Comment by heapwolf** [comment]
@c0b41 excellent! 🍻 🎉
