### ISSUE TITLE
Build broken for older Linux versions

### ISSUE THREAD

**Issue by c0b41** [voltraco/beta#20]
![ekran goruntusu - 2017-02-11 15 43 49](https://cloud.githubusercontent.com/assets/2834954/22853835/cb9a8a64-f068-11e6-804b-b2f116a78723.png)

**Comment by heapwolf** [comment]
This is usually because your systems libs are really old. For the first few Voltra releases i was super concerned about backward compatibility, i was compiling with a crazy old verison of GCC, (4.5 I think). Can you post the output from `uname -a`?

**Comment by c0b41** [comment]
@0x00A 
![ekran goruntusu - 2017-02-14 00 18 44](https://cloud.githubusercontent.com/assets/2834954/22903904/146a6c74-f243-11e6-8839-fb2a327a3284.png)

**Comment by heapwolf** [comment]
Ah yeah, 14.x. Are you on such an old version for development reasons or something?

**Comment by c0b41** [comment]
@0x00A actualy no, elementary os It continues in the old version ..

**Comment by heapwolf** [comment]
eOS is on the 16.04 LTS base as of Loki (which is a fairly recent release)

**Comment by c0b41** [comment]
@0x00A I use freya :/

**Comment by heapwolf** [comment]
Any reason not to update? We could probably be persuaded to make a build more compatible with legacy systems :)

**Comment by c0b41** [comment]
@0x00A most user use freya, also me :)

**Comment by heapwolf** [comment]
I see that Freya is officially unsupported now. Is there a specific reason not to update?

**Comment by c0b41** [comment]
@0x00A Actually there is no reason, also most linux user using old version

**Comment by heapwolf** [comment]
As a linux user, and someone who cares about security, I think people should upgrade, espeically when there are literally hundreds of security fixes that have gone into such a major version release. However, given that its only a few years old, we will consider making a legacy compatible release. For now i will leave this issue open.
