### ISSUE TITLE
Report on successful upgrade to beta2.20 on Fedora

### ISSUE THREAD

**Issue by jberkus** [voltraco/beta#21]
Voltra Folks:

This is a very successful upgrade.  Let's cover all the things that worked:

**AppImage Upgrade**: I installed 2.0 from tarball.  Despite that, when I installed the AppImage into the same directory, Voltra worked perfectly and automatically found the index files from the original beta.

**AppImage Functionality**: works just as well as the tarball, *and* I now have a icon in my application list.  Yay.

**Adding Albums**: I copied some new music files from my Amazon account into ~/Music, and they appeared in Voltra so fast I couldn't catch how long they took.

Some other issues appear to not yet be resolved, but those aren't new and I'll comment on them separately.

So, keep up the good work.  Voltra for Linux is a win.

**Comment by aprile** [comment]
Thanks for the update! Glad to hear you're happy with the Linux version so far.

**Comment by heapwolf** [comment]
👍 Thanks again @jberkus!! I'll archive this for now and add to the list of platforms that Voltra successfully runs on.
