### ISSUE TITLE
Editing more than one song meta data at a time

### ISSUE THREAD

**Issue by themacguru** [voltraco/beta#26]
Sometimes, when editing tracks on a record, I need to edit a few tracks at a time (that may have been mislabeled previously). I can only edit the whole record or select/edit tracks individually now.

**Comment by aprile** [comment]
Thanks, this is a feature we are planning to add.

**Comment by icco** [comment]
This would be awesome. Cleaning up my library, found an album that's really two albums merged together and it's a pain to rename the two. 

![screen shot 2017-08-05 at 9 41 00 am](https://user-images.githubusercontent.com/20201/28995870-3e8c4a34-79c2-11e7-9a90-a601b9ce202b.png)

Would love to be select random tracks in this and mark them in an album. I also really like how iTunes gives you a next button if you need to edit lots of tracks, but still have to tweak one at a time.
