### ISSUE TITLE
Broken image when signing up for beta access

### ISSUE THREAD

**Issue by matheuss** [voltraco/beta#27]
1. Go to [voltra.co](https://voltra.co)
2. Scroll to the very bottom
3. Type your email and hit enter

Then:

![screen shot 2017-03-04 at 2 55 21 pm](https://cloud.githubusercontent.com/assets/4721750/23580980/a2606a78-00ea-11e7-84c3-e4e7b46cd5e9.png)

**Comment by aprile** [comment]
Thanks for pointing this out! We missed this on Mailchimp when we moved over to our new site :)

**Comment by aprile** [comment]
Should be fixed now.
