### ISSUE TITLE
Option to manually rescan watch folders

### ISSUE THREAD

**Issue by matthewmorek** [voltraco/beta#28]
Recently, I've been downloading music from Amazon Music. I found out that I still have to manually launch iTunes to see new albums appear, then relaunch Voltra to populate changes.

This is despite Voltra watching my default iTunes Music folder, and Amazon correctly exporting all downloads to it upon request.

Having a failsafe button that says _Rescan now_ would always save the day for me.

**Comment by aprile** [comment]
This shouldn't be an issue now that the watcher is fixed. And if you do want to rescan a folder you can add it again to your library and it will skip over all the tracks already in there.
