### ISSUE TITLE
[Feature] Remember window position and size

### ISSUE THREAD

**Issue by matthewmorek** [voltraco/beta#3]
In `v1.10.5` Voltra introduced an updated design, and by default launches a quite huge window now. It would be great if it could remember its window's last size/position for consistency.

On an iMac 5K the default size is definitely overwhelming.

**Comment by aprile** [comment]
I believe this has been addressed, (if not position, at least size). And Voltra remembers the position now for mini/micro versions.

**Comment by aprile** [comment]
Still not properly addressed, we need to revisit.

**Comment by aprile** [comment]
Okay, we are part of the way there with this, now it won't open to a massive size on start, but still working on remembering size and position.
