### ISSUE TITLE
No albums are picked up after import to watch directory

### ISSUE THREAD

**Issue by matthewmorek** [voltraco/beta#30]
I've struggled today to add a new album downloaded off Amazon Music to Voltra.

#### To reproduce
1. Import music to iTunes (should pick it straight away);
2. Launch Voltra;
3. See no new albums;
4. Re-launch iTunes;
5. Re-launch Voltra;
6. Still see no new albums;
7. Hide under the desk and weep; 😢

#### Version
`v2.5.1`

**Comment by aprile** [comment]
Oh no! We figured out that the watcher wasn't working reliably for this version. This is fixed in the latest.
