### ISSUE TITLE
Text highlight appears illegible

### ISSUE THREAD

**Issue by matthewmorek** [voltraco/beta#31]
I've noticed that text highlight in editable fields is illegible, while it should probably adhere to WCAG2 guidelines.

![screen shot 2017-03-08 at 18 37 58](https://cloud.githubusercontent.com/assets/1137994/23747899/463d32f8-04b9-11e7-8b6b-6185c06d7979.png)

**Comment by aprile** [comment]
We fixed this issue in the latest release (2.5.3)!
