### ISSUE TITLE
Open preferences crashes app

### ISSUE THREAD

**Issue by kristojorg** [voltraco/beta#35]
Opening system preferences via menu bar or CMD + , causes a fatal error `cannot read property click of null`. See image below.

It looks like when setting the application menu using electron `setApplicationMenu` the "Preferences..." option calls click on null element due to a bad query selector: `'section.profile a[data-area="settings"]'`. I believe what you meant was: `'nav a[data-section="settings"]'`. 

Happy to help debug more if you'd like. 

<img width="1366" alt="screen shot 2017-03-13 at 5 43 01 pm" src="https://cloud.githubusercontent.com/assets/4398775/23881924/d0101338-081a-11e7-9a89-58c8cb331c4f.png">

This is where I think the bad query selector is (line 14816): 

<img width="619" alt="screen shot 2017-03-13 at 6 25 31 pm" src="https://cloud.githubusercontent.com/assets/4398775/23881925/d4e2ad8a-081a-11e7-84d7-ad26d38a1400.png">

**Comment by aprile** [comment]
Thanks @kristojorg ! We already fixed this issue and we'll be sending an autoupdate shortly.
