### ISSUE TITLE
International availability?

### ISSUE THREAD

**Issue by rnkn** [voltraco/beta#36]
While I eagerly await a beta invite, can I ask, in which countries will Voltra streaming be available?

I'm in Australia. I like music. Spotify sucks.

**Comment by aprile** [comment]
We're sending out invites in a few batches over the next week! So you should get yours shortly.

We will be offering our services internationally from the start, though the catalogs for each country might be a little different depending on regional restrictions that some labels impose. We'll be launching the store as soon as we have 10 million tracks :)

**Comment by rnkn** [comment]
I must have missed the last batch, I guess I'll just need to wait for...

![ekbixdgtrmzs4aa9ks71fyz8yeq](https://cloud.githubusercontent.com/assets/1256849/24347411/951bf5f6-131b-11e7-88d3-cb5a51c083ab.jpg)

**Comment by aprile** [comment]
You should receive an invite this week!
