### ISSUE TITLE
playback stops when playing from an artist page

### ISSUE THREAD

**Issue by kristojorg** [voltraco/beta#37]
When I press "play all" from an artists page, the playback stops after every song. This is what player looks like after completion of a song:

<img width="1408" alt="screen shot 2017-03-19 at 1 25 48 pm" src="https://cloud.githubusercontent.com/assets/4398775/24083116/9c78e824-0ca7-11e7-99c3-c2b228a487eb.png">

It just doesn't move on to the next song until "next" is pressed.

**Comment by aprile** [comment]
Hey @kristojorg 

We are still trying to get to the bottom of this issue, which seems to only happen randomly. It has nothing to do with the artist screen, I've experienced it before other places in the app. 

So this will be fixed when we're able to reliably reproduce.

**Comment by kristojorg** [comment]
Okay, let me know if there is something I should look for when it happens

**Comment by aprile** [comment]
We think we fixed this issue in 2.5.12, let us know if it happens again.
