### ISSUE TITLE
Album covers not being cached?

### ISSUE THREAD

**Issue by jberkus** [voltraco/beta#38]
I just used voltra for the first time on a really poor internet connection.  I was surprised to find that album covers didn't load.

It appears that album covers aren't being stored, but are being re-loaded from the internet every use?  Can you change that?

If that's not the case, then this is some other issue.

beta 2.2 / Fedora / AppImage

**Comment by heapwolf** [comment]
Images are not loaded from the internet, they are stored on your machine, they are embedded inside your audio files. 

The latest release is 2.5.3, maybe try updating to the latest and see if the problem is reproducible.

**Comment by jberkus** [comment]
OK, then there's something else wrong, because the album covers definitely aren't loading if I don't have internet.

This is the Linux version from 2 weeks ago; I thought that was 2.2 (there's no version number in the actual UI).

**Comment by aprile** [comment]
The covers don't load from the internet, they are stored locally on your computer. So you are saying that there is a reproducible issue where your album art doesn't load whenever you are offline? Can you take a video for us? We haven't heard about this before.

**Comment by jberkus** [comment]
I'll make one as soon as I get back from my current trip.

**Comment by jberkus** [comment]
I can't seem to reproduce this under slow and no-internet situations anymore, so I'm going to assume that the issue was circumstantial and close this bug.
