### ISSUE TITLE
Use JavaScript facial detection for auto-cropping artist images

### ISSUE THREAD

**Issue by rnkn** [voltraco/beta#43]
Sometimes the downloaded artist images can look really nice. But when the cropping cuts heads/eyes off, not so nice.

Luckily facial detection can be performed client side with JavaScript: http://liuliu.me/ccv/js/nss/

And you'll never need to decapitate an artist again!

**Comment by aprile** [comment]
Good idea, but this one doesn't seem to work... I will open an internal issue to look for a solution.

**Comment by rnkn** [comment]
Yeah seems to fail at retrieving an image from URL, but works okay when uploading an image.

**Comment by aprile** [comment]
Hmm, I actually tried uploading an image, not from a URL.
