### ISSUE TITLE
Maximise button is not supporting expanding mode on OSX

### ISSUE THREAD

**Issue by monocursive** [voltraco/beta#44]
Hi Voltra team!

OS: 
OSX

Description: 
When I hold alt key + I click expand button, Voltra goes fullscreen
![image](https://cloud.githubusercontent.com/assets/2698317/24778589/bd6a0d46-1b2b-11e7-9169-17c8767ea4fa.png)

Expected:
It should maximise the window without going fullscreen
![image](https://cloud.githubusercontent.com/assets/2698317/24778598/c28ba0be-1b2b-11e7-8989-7b7afac775c7.png)

only [setFullScreen(true)](https://electron.atom.io/docs/api/browser-window/#winsetfullscreenflag) is used,  [maximize()](https://electron.atom.io/docs/api/browser-window/#winmaximize) should be available too.

In the maximize function line 95 of window/index.js, maybe by setting a listener on alt keydown and keyup, so it copies the native behavior. I haven't found a way to copy the native behavior with integrated electron events. setFullScreenable is just disabling the maximize button completeley.
It might just be me that can't read a doc properly, in that case, sorry it's late here ¯\_(ツ)_/¯

---
Update: Actually, there seems to be something to do with fullscreenable: the doc says :

> fullscreenable Boolean (optional) - Whether the window can be put into fullscreen mode. On macOS, also whether the maximize/zoom button should toggle full screen mode or maximize window. Default is true.

Update again: 
Ah you're using frame: false in windowOptions and draw your own controls, back to the key event handler I guess. 
Not being able to just maximize instead of fullscreen is not a big deal, but I'm used to maximise windows, so every time I open Voltra I get this big slow FullScreen animation, muscle memory can sometimes be a pita.

**Comment by aprile** [comment]
Hey! Thanks for this, we will be adding maximize to the next version.

**Comment by heapwolf** [comment]
Fixed
