### ISSUE TITLE
Trying to select multiple artists by shift clicking opens a new browserWindow with an error

### ISSUE THREAD

**Issue by monocursive** [voltraco/beta#45]
OS:
OSX

I tried to select multiple artists by selecting an artist and then shift clicking another one.
There is absolutely no real use for this atm, but as it is the native way to select a group of items, some users might try to do that. 

Screenshot of the error: 
<img width="896" alt="screen shot 2017-04-07 at 02 11 18" src="https://cloud.githubusercontent.com/assets/2698317/24780471/edcd5270-1b37-11e7-95e7-cf3b4da4d5d8.png">

**Comment by monocursive** [comment]
Late at night idea : 

Allow multiple artists selection with either native controls for multi select and automatically create a playlist from the selected artists.

----
Edit: the automatically part is probably a bad idea.

**Comment by heapwolf** [comment]
The clicking is now fixed in the current release tag (2.6.0), but selecting multiple artists isn't implemented yet.

**Comment by heapwolf** [comment]
Fixed
