### ISSUE TITLE
Geolocation API key exceeding quotas

### ISSUE THREAD

**Issue by monocursive** [voltraco/beta#47]
Ok, this one is weird and very very low priority.
Some plugins might need geolocation and the Google API key provided by Electron is a default one, bundled with every electron app, so its daily quota is rapidly exhausted.

You can get a new one reserved to Voltra and set it on init.
`process.env.GOOGLE_API_KEY = 'YOUR_KEY_HERE'`

[Relevant doc](https://github.com/electron/electron/blob/master/docs/api/environment-variables.md#google_api_key)

**Comment by heapwolf** [comment]
Added a new api key to the current release tag (`2.6.0`).
