### ISSUE TITLE
Strange issue with the word QUEUE and window dragging on Linux

### ISSUE THREAD

**Issue by jberkus** [voltraco/beta#49]
This is one of those strange issues which I'm reporting, not because I expect a fix, but because you're liable to get it reported in a less coherent fashion and waste time diagnosing it.

Platform: Fedora/AppImage

Version: 2.5.12

Summary: In Play Queue view, mouse clicks on or near the word "Queue" do not allow dragging the window the way the do with other desktop applications.

Workaround: Just click somewhere else on the title bar, and you can drag the window.

Steps:

1. Populate a Play Queue.
2. Start playback.
3. Click on or near the word QUEUE in the title bar and try to drag the window
4. Nothing happens; the window does not move
5. Click a few cm to the left of QUEUE
6. You can drag the window

I expect that this is due to the center portion of the title bar being where the control icons are located in other views.  I recommend a WONTFIX on this, and keeping this issue around for future "cannot drag window" issue reports.

**Comment by aprile** [comment]
This is fixed in the next version
