### ISSUE TITLE
Songs missing from imported library

### ISSUE THREAD

**Issue by zeke** [voltraco/beta#5]
👋 

Giving Voltra another spin. I like the new app icon!

I have my Media Directory set up in Voltra:

![screen shot 2016-09-20 at 1 00 31 pm](https://cloud.githubusercontent.com/assets/2289/18686832/457edb76-7f32-11e6-936b-f772e1e75020.png)

I have some CCR in there:

``` sh
$ mdfind creedence -onlyin ~/Dropbox/Music | grep mp3 | tail -n 3

/Users/zeke/Dropbox/Music/iTunes/iTunes Music/Creedence Clearwater Revival/Misc/Green River.mp3
/Users/zeke/Dropbox/Music/iTunes/iTunes Music/Creedence Clearwater Revival/Misc/Susie Q.mp3
/Users/zeke/Dropbox/Music/iTunes/iTunes Music/Creedence Clearwater Revival/Misc/Lodi.mp3
```

But when I search in artists, I don't see anything:

![screen shot 2016-09-20 at 1 01 15 pm](https://cloud.githubusercontent.com/assets/2289/18686851/5a5c92ea-7f32-11e6-88f0-f0aad612c3a5.png)

Pretty sure these files have ID3 metadata too..

**Comment by heapwolf** [comment]
Is this after a fresh install? If you've had the beta for a while and this is an update, one thing you might want to try is to hit the reset button (under settings)...

![image](https://cloud.githubusercontent.com/assets/136109/18742798/61988994-80b6-11e6-8e71-7cf0675e9580.png)

Can you try that and then try adding the music again?

**Comment by zeke** [comment]
I pushed [RESET DATA] and the app crashed instantly. Just disappeared. On manual restart, I see a nice welcome screen again.

Started the import again but it seems to be hanging...

![screen shot 2016-09-22 at 10 44 29 am](https://cloud.githubusercontent.com/assets/2289/18759519/a2c0dd90-80b1-11e6-93af-4669ae171b5e.png)

Can I share a debug log somehow?

**Comment by heapwolf** [comment]
Did it crash or just quit? It should just quit. But you can open the web inspector by pressing alt+command+i, that should show the console and any errors.

**Comment by zeke** [comment]
![screen shot 2016-09-22 at 11 09 37 am](https://cloud.githubusercontent.com/assets/2289/18760238/18f73c7c-80b5-11e6-8721-29fb2ffec1b0.png)

**Comment by heapwolf** [comment]
That output looks correct-ish (strange that you dont have a username or email). But it shouldn't crash or hang from that, looks like it handled the error and logged it. Did you download that track originally from iTunes?

**Comment by zeke** [comment]
Not sure where that track came from. I deleted that whole directory and tried again. Same result, but no console errors this time around:

![screen shot 2016-09-22 at 11 58 16 am](https://cloud.githubusercontent.com/assets/2289/18761964/dda0c1aa-80bb-11e6-8e9b-7858bbf28fd5.png)

Another observation: Once the app is in this broken state, I can't quit with <kbd>cmd</kbd><kbd>q</kbd> nor the Menu option:

![screen shot 2016-09-22 at 11 57 09 am](https://cloud.githubusercontent.com/assets/2289/18762067/3436a372-80bc-11e6-9156-4e370834e082.png)

Closing from the context menu in the dock does work, however.

How else can we debug this?

**Comment by heapwolf** [comment]
I'm guessing that when the app starts importing, it looks something like this...

![image](https://cloud.githubusercontent.com/assets/136109/18762575/9a2ee804-8109-11e6-92e0-da158c42dff9.png)

At what point does it turn black? It looks like it makes some progress...

![image](https://cloud.githubusercontent.com/assets/136109/18762592/a96a7aa4-8109-11e6-9d3f-4a4ac4d9361e.png)

Does the progress bar stop?

**Comment by zeke** [comment]
https://cloudup.com/cEA9AM_Tejb

**Comment by heapwolf** [comment]
oh! That's terrible :( Do you get any debug output if you launch the process with the `DEBUG=voltra:*` environment variable?

**Comment by heapwolf** [comment]
also, its interesting because we see that the dev tools is disconnected, making me think perhaps it's something more severe than a javascript error

**Comment by zeke** [comment]
Like this?

``` sh
DEBUG=voltra:* open /Applications/voltra.app
```

Using that command, I don't see any additional output in the web console.

**Comment by heapwolf** [comment]
I invited you to our slack channel via zeke@sikelianos.com :)

**Comment by heapwolf** [comment]
I also created a new release (`1.10.6`) that enables some more debugging info

**Comment by zeke** [comment]
1.10.6 now logs duplicate files, but I don't see any other clues about what's failing. Here's the whole thing: https://gist.github.com/zeke/e6582061d5d83b7aad8351945d843143

**Comment by zeke** [comment]
I just installed version 1.11.0 and am still seeing the same issue. Also ran with `DEBUG=voltra:* open /Applications/voltra.app` but don't see any useful debug info.

**Comment by zeke** [comment]
What about adding a debugging flag that would log every single filename as it is processed? That might help us identify the problem file(s).

**Comment by heapwolf** [comment]
@zeke other beta testers have confirmed that this is resolved. If for you it's not feel free to reopen :)

**Comment by zeke** [comment]
1.12.2 successfully imported everything. Thanks @0x00A! 

🍰 

FYI issue creators cannot re-open issues that are closed by someone else.

**Comment by heapwolf** [comment]
@zeke yyyyyyyahaaaaaaahhhh! 🎉 🌮 🍺 ❤️ 

PS. oh yeah, oops :)
