### ISSUE TITLE
Ad-hoc queue playback keeps halting

### ISSUE THREAD

**Issue by jberkus** [voltraco/beta#51]
* Voltra 2.5.???  (no way to find version in UI)
* Linux, Fedora 24, installed from AppImage

Issue: when playing an ad-hoc queue, playback halts every 4-5 songs.

Steps to reproduce:

1. Create a mixed queue with 4 or more different albums
2. Shuffle the playlist
3. Start playing
4. Votra will play 1-4 tracks.
5. Voltra will stop playback
6. Playback can be resumed by clicking play.

The laptop I'm doing this on is heavily used, so I would suspect some kind of resource issue.  Except: this problem never happened on earlier versions of Voltra Beta I used, and random playlists are my main usage of Voltra, so it seems more likely that it's a bug introduced sometime in the last 2 months (I updated Voltra last about 4 weeks ago).

It is also possibly due to a specific album in my collection, since I've added multiple new albums in the last 3 months.  If I find a patter there, I'll update this issue.

**Comment by jberkus** [comment]
Updating this.  I've found this issue with several albums where I'm just playing the whole album; after about 5 tracks, playback just halts.

**Comment by aprile** [comment]
The Voltra version in Linux / Windows is now in About Voltra under the Help menu :)

We have experienced this a few times but it is difficult to reproduce reliably, this is currently something we are working on a fix for. I am almost positive it has nothing to do with playlists or specific albums.

**Comment by jberkus** [comment]
Yah, it's also not consistent for me.  I thought I had an album where it would consistently halt after 5 tracks, but of course it wouldn't do it while I was watching.   I wouldn't be surprised if this was somehow related to available memory or CPU.

Note that I don't have, as far as I know, any ALAC-encoded tracks, so the other issue reported is not the cause of this.  I do however have a bunch of AAC-encoded tracks, so if AAC has a similar issue ...

**Comment by jberkus** [comment]
So this issue seems to be getting worse either because of my mix of albums or because of changes to Voltra; at this point, I'm lucky if I can play 3 songs in a row before Voltra halts for no apparent reason.  If we can't find a cure for this, I'll have to give up on voltra because I can't keep going back to the console every 9 minutes to restart it.

What can I do to help you reproduce this issue?
