### ISSUE TITLE
Some albums no longer play under Voltra

### ISSUE THREAD

**Issue by jberkus** [voltraco/beta#52]
Platform: Linux/AppImage
Version: 2.5.??? (again, need way to find version number)

As of the last time I updated voltra (about 6 weeks ago), certain albums will no longer play under it.  I can select those albums, and or tracks off them, but play hangs forever and does not proceed.  I was able to play these albums under earlier releases, and they still play if I use RhythmBox.

I don't see anything distinctive about the albums which don't play vs the ones which do.

This may or may not be related to Issue #51.  It's the same release of Voltra.

**Comment by jberkus** [comment]
So, it's still the case that i have a couple of albums that won't play under voltra beta.  One is "Puppet Loosely Strung" by The Correspondants.  

I'm wondering what data I can supply you with to figure out the issue?

**Comment by aprile** [comment]
What is the file type? And if it is an M4A, is it an ALAC?

**Comment by jberkus** [comment]
It's M4A-AAC, as far as I can tell.

**Comment by jberkus** [comment]
I've confirmed that all the albums that don't play are M4A of some kind.  I have M4A encodings installed, so that I can play them under other players.  I suspect that something in how AppImage works means that Voltra doesn't see these optional libraries.

I can work around it by re-encoding the music, but leaving this issue open in case someone at Voltra is in a position to tackle the various M4A playback problems.
