### ISSUE TITLE
Startup error after upgrading to v3.1.0

### ISSUE THREAD

**Issue by matthewmorek** [voltraco/beta#54]
I've just tried to upgrade to v3.1.0 using an auto-update mechanism, and after a restart nothing happened, so I downloaded fresh DMG off the website and replaced the executable in `/Applications` dir, to be greeted by this error upon the start:

```
Error
    at EventEmitter.window.events.on (/Applications/Voltra.app/Contents/Resources/app.asar/src/bundle.js:1:327815)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at process.on (/Applications/Voltra.app/Contents/Resources/app.asar/src/bundle.js:1:328668)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at window.onerror (/Applications/Voltra.app/Contents/Resources/electron.asar/renderer/init.js:135:22)
```

**This now shows all the time and prevents the player from starting properly.**

![screen shot 2017-07-31 at 08 08 38](https://user-images.githubusercontent.com/1137994/28766439-7d20c3b4-75c7-11e7-9cd7-4d972660e2c6.png)

**Comment by heapwolf** [comment]
I removed version `3.1.0` from the site. It should show `3.1.1` as the most current download right now. Can you download that and tell me if you get the same error?

**Comment by matthewmorek** [comment]
Yes, the same error happened after upgrade to `v3.1.1`. A full wipe and reinstall solved the issue (obviously).

**Comment by heapwolf** [comment]
Sounds like the migration script failed to migrate all your data properly. I'll look into this more.

**Comment by matthewmorek** [comment]
What was the migration path like, between `v2.4` and `v3.1.0`? Was there an intermediate release? My auto-updater wasn't picking up anything, if that's the case. Maybe that's why the data migration failed?

**Comment by heapwolf** [comment]
We had to change our signing certificate once again because we didn't include a Mac App Store (MAS) component in the last signing cert. `3.1.3` is now signed with the latest certificate.
