### ISSUE TITLE
Auto-update pops up during music import

### ISSUE THREAD

**Issue by matthewmorek** [voltraco/beta#55]
I've just received an auto-update pop up in the middle of importing music (the process was already ongoing).

This not only obscures the view (so I don't know if the music has been imported yet), but upon clicking "update" the player would likely restart leaving my library in an unfinished state, halfway through importing.

Also, when I clicked "cancel", finished the import and selected "check for updates", I thought that there was a communications problem with the update server, since the app did nothing for at least 20 seconds. I think a separate "checking for updates" pop up would work well to better communicate to users what's going on.

**Version tested:** v3.1.0

**Comment by heapwolf** [comment]
hmm, `3.1.0` has a major problem with it, im surprised you were able to download it. Also, i thought i removed that from the releases.

**Comment by heapwolf** [comment]
> I've just received an auto-update pop up in the middle of importing music (the process was already ongoing).

More importantly, to your original point, yeah, the dialog shouldn't be trying to offer you anything during an import. I'll move the check for this to *after* the import completes. 👍

**Comment by matthewmorek** [comment]
> hmm, 3.1.0 has a major problem with it, im surprised you were able to download it.

It actually popped up as an auto-update at first, but I was able to download `v3.1.0` from the website, so maybe I've done it just before you removed it?

**Comment by heapwolf** [comment]
Ah, yeah, you might have grabbed it right before I deleted it. Any luck with the new one? @juliangruber just wrote some nice tests for automatic updates, so we should have a way smoother experience in the future.

**Comment by heapwolf** [comment]
Fixed in `3.1.3`.
