### ISSUE TITLE
What Software License will Voltra Use?

### ISSUE THREAD

**Issue by baimafeima** [voltraco/beta#56]
Under what license will Voltra Player be released? Will you make any public beta releases here on GitHub?

**Comment by heapwolf** [comment]
Hi @baimafeima we don't have any plans at the moment to open source the Voltra desktop or mobile players. 

We do expect to continue to open source some of the components and modules that we develop. 

We'll also continue to contribute time, resources and money to the underlying open source projects that our software is built on.

**Comment by baimafeima** [comment]
> We'll also continue to contribute time, resources and money to the underlying open source projects that our software is built on.

Thanks for the updates @0x00A Which open source projects are these and wouldn't their licenses actually permit for code to be reused as a closed source project?

That being said, I would actually like to encourage you to open source your code. If I want to "own" my music as your tagline on your website says, why would I want to rely on a music player I have no right to "own" itself?

**Comment by heapwolf** [comment]
@baimafeima we use FOSS that is MIT License or compatible. Electron for example. I appreciate your desire for 100% of everything to be open source. There are a whole host of great music related projects that are, you might try checking out some of those! 👍
