### ISSUE TITLE
Credit Card entry is hard in dark mode

### ISSUE THREAD

**Issue by icco** [voltraco/beta#57]
![screen shot 2017-08-05 at 9 26 56 am](https://user-images.githubusercontent.com/20201/28995794-94a032ca-79c0-11e7-8721-a12e218828cb.png)

As you type in credit card info into Stripe, the text changes from white (the placeholder text) to black, which I can't read at all.

**Comment by aprile** [comment]
Ah thanks, we will fix this ASAP!

**Comment by aprile** [comment]
Fixed in the next release
