### ISSUE TITLE
Typo in alert dialog

### ISSUE THREAD

**Issue by icco** [voltraco/beta#59]
![screen shot 2017-08-05 at 11 00 34 am](https://user-images.githubusercontent.com/20201/28996377-6ed4fff0-79cd-11e7-8641-f9420a0986a4.png)

Error was

```json
{
  "reasons": [
    {
      "reason": "Could not get the album reference",
      "location": "/Applications/Voltra.app/Contents/Resources/app.asar/src/bundle.js:1:267799"
    }
  ]
}
```

Missing an `e` in `the cloud`.

**Comment by aprile** [comment]
Fixed in the next release
