### ISSUE TITLE
Inherit OS audio settings

### ISSUE THREAD

**Issue by matthewmorek** [voltraco/beta#60]
After doing some audio testing between different audio players and apps on my Mac, I have noticed that Voltra does not adhere to system-wide audio configuration settings, with exception of volume.

It makes it impossible to configure the sound equalisation to appropriate level using tools such as Boom (http://www.globaldelight.com/boom/index.php), because none of these settings are being passed on to Voltra, or are being overridden by internal audio configuration/equalisation.

I consider this to be a bug, because it prevents me from using a properly configured audio profile for my system, which in turn prevents me from listening to music in full fidelity.

Samples in `m4a` format attached.

[audio_samples.zip](https://github.com/voltraco/beta/files/1225282/audio_samples.zip)

**Comment by heapwolf** [comment]
> none of these settings

Do you mean eq settings from Boom?

**Comment by matthewmorek** [comment]
Yup. Definitely. No system-wide equalisation settings are being passed onto Voltra, or the app overrides them with its own settings.

**Comment by aprile** [comment]
This is fixed in the next version
