### ISSUE TITLE
Flatpak or Snap

### ISSUE THREAD

**Issue by baimafeima** [voltraco/beta#61]
Would you consider a Flatpak or Snap release for easy cross-platform installation?

**Comment by heapwolf** [comment]
Woah, Flatpak looks really cool, I'd never heard of it before. We'd be happy to add Snap for this coming release and also look into Flatpak.

**Comment by juliangruber** [comment]
Both look like AppImage alternatives, would they be an improvement in your opinion?

**Comment by baimafeima** [comment]
As far as I know, Flatpak and Snap are superior to AppImages in terms of security. Flatpaks can be heavier on resources than Snaps. Fully confined Snaps cannot snoop on each other or affect the rest of the system. AppImages perform more like executable files. Poking @probonopd from AppImage and @alexlarsson from Flatpak to find out more.

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) has, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

> As far as I know, Flatpak and Snap are superior to AppImages in terms of security

AppImages can run in sandboxes such as [Bubblewrap](https://github.com/projectatomic/bubblewrap) (the one that Flatpak uses) or [Firejail](https://firejail.wordpress.com/), at the option of the user. By default, AppImage does not require nor enforce a sandbox. I would only run Voltra Desktop Player if I trust its developers anyway, and I would only want to run it if I knew where it was coming from (the original developers).

Read [here](https://plus.google.com/+LinusTorvalds/posts/WyrATKUnmrS) what __Linus Torvalds__ had to say about AppImage security (make sure to click on "show all comments").

> The whole "omg, the sky is falling" security argument is bogus. It's particularly bogus for non-core user-centric applications (ie the stuff that doesn't come with the distribution, and that the distribution makes actively impossible to build).

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by heapwolf** [comment]
Hey @probonopd, we're sold on building `AppImage` packages :) And as per issue #62, we will ensure there is a download link for this upcoming release so you can add Voltra to AppImageHub.

PS. @baimafeima we just added `Snap` packages for this upcoming build 👍

**Comment by baimafeima** [comment]
@0x00A I didn't find the snap package in the drop-down menu on your website: https://voltra.co/desktop/linux/
Is it available somewhere else?

**Comment by heapwolf** [comment]
@baimafeima Hey, we added it but we found that it had some issues, we will need to defer it until later. @juliangruber might be able to report on the specifics about why it wasn't working.

**Comment by juliangruber** [comment]
I couldn't get snap working with Travis, `snapcraft` failed to install:

```
Job for snap.mount.service failed. See 'systemctl status snap.mount.service' and 'journalctl -xn' for details.
dpkg: error processing package snapd (--configure):
```

**Comment by baimafeima** [comment]
I know that @ikeydoherty, founder and lead developer of Solus, is currently working on implementing snaps into the Solus Software Center. I am not affiliated with the project but maybe this is a good time to look at this, especially since I've heard about "base snaps", if I remember correctly, the possiblity to optimize snaps for specific systems. If you were to offer a downloadable snap via your website, would there still be an option to optimize it for Solus on the Solus-side? I can't wait to have Voltra available as I find it a much better alternative to Spotify and I really hope this project will take off.

**Comment by heapwolf** [comment]
Still looks like there is an upstream dependency preventing this from being added.

**Comment by baimafeima** [comment]
Which upstream dependency? @0x00A

**Comment by baimafeima** [comment]
@hxoht @juliangruber Now that Flatpak has reached 1.0 (https://flatpak.org/press/2018-08-20-flatpak-1.0/) could you make Voltra available? I'm using Linux-based operating systems and AppImages just don't cut it for me due to their lack of sandboxing. I'd definitely prefer a properly sandboxed solution via snaps or flatpaks.

**Comment by baimafeima** [comment]
Another argument for Flatpaks: Two hugely popular operating systems, Solus and MX Linux provide Flatpak support out-of-the-box. MX Linux already integrates them neatly into their package manager as you can see [here](https://mxlinux.org/flatpak-applications-now-available-through-mx-package-installer) and Solus new Software Center will feature flatpaks to be installable with a simple click.

**Comment by baimafeima** [comment]
@hxoht @juliangruber Is this project dead? The website has been inaccessible for a long time. Could you please update regarding the status of this project? Is there a possibility to go open source so that other people can start working on it?

**Comment by heapwolf** [comment]
@baimafeima Voltra has been discontinued. The announcement was on a blog a long time ago. Sorry for not closing out these issues.
