### ISSUE TITLE
Please provide application for download

### ISSUE THREAD

**Issue by probonopd** [voltraco/beta#62]
Right now users have to log in to download the application. It would be better if it was the other way around, i.e., if everyone could download the application and only then log in.

This would also allow me to put the application into https://github.com/AppImage/AppImageHub where it would be picked up by many sites (hey, free advertising!)

Reference:
AppImage/AppImageHub#15

**Comment by aprile** [comment]
Hey, I tried to fork it but there was a problem. The link is now up at [voltra.co/desktop/linux](https://voltra.co/desktop/linux)

**Comment by probonopd** [comment]
Thank you very much for providing a download link. Added to https://github.com/AppImage/appimage.github.io/pull/68/files
