### ISSUE TITLE
Global Shortcuts (Linux)

### ISSUE THREAD

**Issue by c0b41** [voltraco/beta#65]
voltra app always listening global shortcuts, i think voltra app only listen [Shortcuts within a BrowserWindow](https://electron.atom.io/docs/tutorial/keyboard-shortcuts/#shortcuts-within-a-browserwindow) because other apps blocking shortcuts event

https://www.useloom.com/share/f3b6506153334b469589cc9c686a339f

**Comment by aprile** [comment]
Thank you for bringing this to our attention, we will fix it in the next release.
