### ISSUE TITLE
Voltra turns gray-black at random occasions and there's no UI

### ISSUE THREAD

**Issue by mttjhn** [voltraco/beta#7]
When running Voltra 1.11.1, I tried importing, and while it was importing, I moved the application to a different display. Voltra turned gray and there was nothing I could click, no status or progress, no buttons. I eventually force-quit the applicaiton. Then, I opened it again. My albums showed, but I clicked on the playlist option. The application turned the gray-black color and nothing showed. Now I can't get it to go back to Albums, even when using the View->Albums menu. See screenshot below for what Voltra looks like.

Seems really buggy for a final beta. :(

![voltra-frozen](https://cloud.githubusercontent.com/assets/1553972/19652959/fb9828ce-99cf-11e6-8b5f-c06d7f28cbaf.png)

**Comment by heapwolf** [comment]
marking as fixed as per slack conversation

![image](https://cloud.githubusercontent.com/assets/136109/19665346/d94c4622-9a44-11e6-8068-612b22af9719.png)
