### ISSUE TITLE
[Desktop] Auto-update progress indicator

### ISSUE THREAD

**Issue by matthewmorek** [voltraco/beta#74]
#### Background
A big part of the app is its ability to auto-update itself, but I have noticed that the most annoying is the lack status of the update process. Apps that offer an auto-update feature on Mac or Windows have some sort of indicator that shows the current status and progress during the process.

#### Issue
Voltra currently does auto-updating completely in the background, notifying only when its ready to restart and install the update (whenever that is).

#### Impact
Hiding auto-update indication causes uncertainty and lack of awareness of what's happening in the background, leading to frustration when a user might expect an update to be downloaded within a reasonable timeframe (subjective).

#### Steps to reproduce
1. Open Voltra.
2. From the _File_ menu select _Check for updates_.
3. Wait an unknown amount of time while the app checks for updates in the background without indicating what it's doing.
    - If an update is not available an information is displayed reasonably fast;
    - If an update is available you need to wait an unspecified amount of time for the update to download and display the update dialog;

#### Details
```
Voltra for Desktop (Mac) v3.3.0
macOS 10.12.6 (16G1036)
```

**Comment by aprile** [comment]
We've added this to our to do list!
