### ISSUE TITLE
[Desktop] Provide a global indicator of tracks being synced

### ISSUE THREAD

**Issue by matthewmorek** [voltraco/beta#75]
#### Issue
Syncing tracks from VAA is an amazing feature, but lacks a way to quickly view a list and progress of current syncing operation.

#### Impact
In order to find out which tracks/albums are being synced a user needs to scroll through a list of albums and once identifying an album with a "sync" icon display album details (track list) to see which tracks have been/are being synced.

#### Steps to reproduce
As per _Impact_ section above.

#### Details
```
Voltra for Desktop (Mac) v3.3.0
macOS 10.12.6 (16G1036)
```

**Comment by aprile** [comment]
Thanks for your feedback @matthewmorek :) We are working on improvements to sync UI and this will most definitely be one of them.

One way currently to see what has been synced is using the Track View and sorting the sync column to see what tracks are synced.

**Comment by matthewmorek** [comment]
Glad to hear this! One way I'd imagine to represent the sync progress could be via sync indicator by showing a circle representing overall sync progress instead of a rotating double-arrows.

![voltra-sync-progress 2x](https://user-images.githubusercontent.com/1137994/34731619-bd01e068-f55a-11e7-9b56-0b042c403fc8.png)

On hover, it could show more sync details, such as:
```
Syncing track 123 of 1234
```
![voltra-sync-progress-details 2x](https://user-images.githubusercontent.com/1137994/34731626-c4686282-f55a-11e7-91e2-aadc93db571c.png)

Just food for thought!
