### ISSUE TITLE
Feature Request: Add shuffle and repeat buttons to control panel

### ISSUE THREAD

**Issue by mkpt** [voltraco/beta#77]
I am using the Mac Desktop App. To turn on shuffle or repeat, I have to remember keyboard shortcuts or use the taskbar menu. I'd like to just have buttons to shuffle or repeat, and I'd like them to be accessible from the main control panel, shown below.

![](https://i.imgur.com/GgsaZ4o.png)

**Comment by aprile** [comment]
Thanks for the feedback, we are working on the design for a new control bar that incorporates shuffle/loop icons, so this will also be implemented in the player shortly.
