### ISSUE TITLE
When a song finishes in the "artist" view, it does not go to the next song. I'd like to just be able to play all of the songs for a given artist.

### ISSUE THREAD

**Issue by mkpt** [voltraco/beta#78]
When viewing songs for an artist, there's no way to play all of the songs for that artist without manually starting the next song by clicking on it. In the example below, if I click the first song "Sloop John B," the application plays it, but doesn't start playing the next song when that song finishes. I have to manually click each song.

![](https://i.imgur.com/IsTlHM2.png)

I'd like to be able to play all of the songs pictured above with one click. Maybe a "Play all" button would suffice.

**Comment by aprile** [comment]
Hi @mkpt !

The play button next to `The Beach Boys` is the Play All button (to play all tracks by an artist). We will consider a way to make this more clear.

**Comment by aprile** [comment]
Closing, since we already have the play all button!
