### ISSUE TITLE
Software update popup gets clipped inside a window

### ISSUE THREAD

**Issue by matthewmorek** [voltraco/beta#8]
As per the title, the software update popup notification gets clipped, if a player windows is not adequately large enough to fit it.

Maybe it should rely on OS-native dialogs instead?

![screen shot 2016-10-26 at 19 29 08](https://cloud.githubusercontent.com/assets/1137994/19739430/c6ad8ebc-9bb2-11e6-97c2-d9be94665d56.png)

**Comment by heapwolf** [comment]
This is fixed in the upcoming release.
