### ISSUE TITLE
[Desktop] No sync indicator in album view for new albums

### ISSUE THREAD

**Issue by matthewmorek** [voltraco/beta#81]
### Issue
New albums are not marked as synced in the album view, despite individual tracks being synced to VAA.

### Impact
Mainly visual; confusion as to whether a given album has been synced or not.

### Steps to reproduce
1. Add a new album to a directory where Voltra watches for music.
2. Wait for Voltra to pick up the new album.
3. Wait for Voltra to sync album to VAA or force sync via album submenu.

### Expected result
Voltra should indicate in album view that an album has been synced to VAA.

### Actual result
<img width="704" alt="image" src="https://user-images.githubusercontent.com/1137994/36025736-0830b200-0d8c-11e8-9b6e-418303c2b388.png">

![screen shot 2018-02-09 at 11 26 48](https://user-images.githubusercontent.com/1137994/36025790-44546312-0d8c-11e8-9de7-13f74598652c.png)

### Details
```
Voltra for Desktop (Mac) v3.4.1
macOS 10.12.6 (16G1036)
```

**Comment by aprile** [comment]
Thank you for this most comprehensive issue 💯 🙂 

This certainly looks like a bug, we'll fix this for the next version!
