### ISSUE TITLE
[macOS] Playback stops when entering lockscreen

### ISSUE THREAD

**Issue by matthewmorek** [voltraco/beta#83]
### Issue
Whenever Voltra plays music and I want to lock the screen (not put the computer to sleep) it stops playback, and resumes it only after unlocking the computer again. Any other app that I tried, including iTunes, keeps playing the music after locking the screen.

### Steps to reproduce
1. Launch Voltra and play some music
2. Lock the Mac via _User menu_ > _Login window..._ or via Alfred > _Lock_
3. Unlock to resume playback

### Details
```
Voltra for Desktop (Mac) v3.4.1
macOS 10.12.6 (16G1036)
```

**Comment by aprile** [comment]
Hmm, I can't seem to reproduce this by locking from the menu (but for me it's  > Lock Screen). 

Is there a different method to reproduce, and is it still happening for you? Are you logging out or just locking the screen?

**Comment by matthewmorek** [comment]
I don't have that menu option (not on High Sierra yet), so I'm usually locking with either of the aforementioned methods: "user" menu or via Alfred's built-in "Lock" command.

Locking with ⌃+⇧+⏏ doesn't interrupt audio, although it turns the display off (and doesn't lock the screen either) instead of showing the lock screen (with a password prompt).

I have a feeling that Alfred's "Lock" command basically engages "Switch user" Mac funtionality, which stops playback of anything, even iTunes.

Please, ignore this bug report. It's probably Apple's totally dumb approach to understanding what "lock the screen" should look like on a Mac. 😄
