### ISSUE TITLE
Successful test for 3.4.1+Fedora+XPS13

### ISSUE THREAD

**Issue by jberkus** [voltraco/beta#86]
Successful test with Voltra operating correctly.

Version: 3.4.1
Platform: Fedora Linux 27
Installation Method: AppImage
Windowing: Wayland
Hardware: Dell XPS 13, both using internal speakers, and using USB speakers.
Formats Tested: MP3, using the standard Fedora Library.  

M4A not tested yet, as changes to Fedora's AAC support have made installing support for this codec more complicated.

As always, please close this issue once you've seen the successful test.

**Comment by aprile** [comment]
Thanks!
