### ISSUE TITLE
Voltra beta is over

### ISSUE THREAD

**Issue by heapwolf** [voltraco/beta#92]
Voltra has been discontinued.

**Comment by jberkus** [comment]
:-(

Damn, that's sad.  I really liked it, probably the best desktop music player I've seen in years.

**Comment by smcconne** [comment]
^ Agreed. Beautiful design, still hoping it goes open source so the community can build on this excellent player and maybe work out a few of the kinks present in the current version. I haven't found anything like it before or since.

**Comment by baimafeima** [comment]
The best way forward would be to open source it. In fact, I believe this is the only way for it to survive.

**Comment by aprile** [comment]
As per the announcement (posted on the blog a while back), we will be releasing an open source version, we don't have a specific release date but it is something we intend to do.

**Comment by baimafeima** [comment]
@aprileelcich Is this blog post still to be found? Why did you ultimately decide to discontinue Voltra?

**Comment by heapwolf** [comment]
Creating a music player wasn't the hardest part (although many people underestimate the complexity involved — you'd never believe how many times people popped up to say "I'm building this" but they never had anything to show, or "come on guys, this is so simple, just get this right", but didn't intend on becoming paying customers). Ultimately, the reason we shut this down was, the major labels are really difficult to work with. They have a monopoly and the music industry is structured to lock out innovators who threaten its traditional model of economics. They didn't like our idea for having a decentralized music store because even though payments would go from the buyer to the catalog holder (major label) payments could also go directly between buyers to the artists. It feels like major labels and large catalog holders are especially averse to anything that facilitates p2p-economics.

**Comment by jberkus** [comment]
@hxoht I hear you.  Back in the 90's I was part of a digital jukebox startup that also failed for the same reason (did you know that one company had a monopoly on jukeboxes over most of the US?).

FWIW, and for your next startup: there wasn't any opportunity for enthusiastic users, like me, who didn't need ocloud storage to become paying customers.

**Comment by franktopel** [comment]
Any updates on the plans for open sourcing Voltra?
